In [ ]:
# integer encoding technique
# convert test into vector

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM

In [2]:
docs = [
    "india is a great country",
    "india has a rich history",
    "cricket is popular in india",
    "virat kohli is a great batsman",
    "ms dhoni is a legendary captain",
    "sachin tendulkar is god of cricket",
    "we love indian cricket team",
    "india will win the world cup",
    "hard work leads to success",
    "practice makes a person perfect"
]

In [3]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)

word_index = tokenizer.word_index
vocab_size = len(word_index) + 1

print("Vocabulary Size:", vocab_size)
print(word_index)

Vocabulary Size: 41
{'is': 1, 'a': 2, 'india': 3, 'cricket': 4, 'great': 5, 'country': 6, 'has': 7, 'rich': 8, 'history': 9, 'popular': 10, 'in': 11, 'virat': 12, 'kohli': 13, 'batsman': 14, 'ms': 15, 'dhoni': 16, 'legendary': 17, 'captain': 18, 'sachin': 19, 'tendulkar': 20, 'god': 21, 'of': 22, 'we': 23, 'love': 24, 'indian': 25, 'team': 26, 'will': 27, 'win': 28, 'the': 29, 'world': 30, 'cup': 31, 'hard': 32, 'work': 33, 'leads': 34, 'to': 35, 'success': 36, 'practice': 37, 'makes': 38, 'person': 39, 'perfect': 40}


In [4]:
input_sequences = []

for sentence in docs:
    token_list = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1, len(token_list)):
        n_gram = token_list[:i+1]
        input_sequences.append(n_gram)

print(input_sequences[:10])

[[3, 1], [3, 1, 2], [3, 1, 2, 5], [3, 1, 2, 5, 6], [3, 7], [3, 7, 2], [3, 7, 2, 8], [3, 7, 2, 8, 9], [4, 1], [4, 1, 10]]


In [5]:
max_len = max([len(seq) for seq in input_sequences])

input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

print("Max Length:", max_len)
print(input_sequences[:5])

Max Length: 6
[[0 0 0 0 3 1]
 [0 0 0 3 1 2]
 [0 0 3 1 2 5]
 [0 3 1 2 5 6]
 [0 0 0 0 3 7]]


In [6]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

# One-hot encoding for output
y = tf.keras.utils.to_categorical(y, num_classes=vocab_size)

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (44, 5)
y shape: (44, 41)


In [7]:
model = Sequential()

model.add(Embedding(vocab_size, 50, input_length=max_len-1))
model.add(LSTM(100))
model.add(Dense(vocab_size, activation='softmax'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 6s 62ms/step - accuracy: 0.0455 - loss: 3.7140
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.1591 - loss: 3.7061
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.1591 - loss: 3.6993
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.1364 - loss: 3.6919
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.1591 - loss: 3.6840
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.1364 - loss: 3.6746
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.1136 - loss: 3.6641
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.1136 - loss: 3.6506
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.1136 - loss: 3.6345
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.1136 - loss: 3.6132
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.1136 - loss: 3.5849
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.1136 - lo

In [ ]:
def predict_next_word(model, tokenizer, text, max_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    token_list = pad_sequences([token_list], maxlen=max_len-1, padding='pre')

    predicted_id = int(np.argmax(model.predict(token_list), axis=-1)[0])

    for word, index in tokenizer.word_index.items():
        if index == predicted_id:
            return word

In [12]:
input_text = "india is a"
print("Input:", input_text)

next_word = predict_next_word(model, tokenizer, input_text, max_len)
print("Next Word:", next_word)

Input: india is a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step
Next Word: great


In [13]:
model.save("next_word_model.h5")
print("Model saved successfully!")

Model saved successfully!


In [14]:
import pickle

# Save tokenizer
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

print("Tokenizer saved!")

Tokenizer saved!


In [16]:
from tensorflow.keras.models import load_model

loaded_model = load_model("next_word_model.h5")
print("Model loaded successfully!")

Model loaded successfully!


In [17]:
with open("tokenizer.pkl", "rb") as f:
    loaded_tokenizer = pickle.load(f)

print("Tokenizer loaded!")

Tokenizer loaded!


In [18]:
input_text = "india is a"

next_word = predict_next_word(loaded_model, loaded_tokenizer, input_text, max_len)

print("Input:", input_text)
print("Predicted Next Word:", next_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
Input: india is a
Predicted Next Word: great
